# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.henningp.de/jax/bizdevops
  tag: stable
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
service:
  enabled: true
  name: web
  type: ClusterIP
  url: https://henningp.de
  externalPort: 5000
  internalPort: 5000
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
